apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metrics-app
  labels:
    app: prometheus-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-metrics-app
  template:
    metadata:
      labels:
        app: prometheus-metrics-app
    spec:
      containers:
      - name: prometheus-metrics-app
        image: localhost:5001/prometheus-metrics-app:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-app
spec:
  selector:
    app: prometheus-metrics-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
